EC90 Use 'Cast' instead of 'Select' to cast: MA0078
green-code-initiative/creedengo-rules-specifications pull request #309
Opened 2024-05-29 15:31 UTC by ElyesFakhar

2024-05-31 06:26 UTC, Djoums commented
Lacks the json file in the EC90 folder, and needs to update changelog.md and rules.md.

2024-05-31 18:58 UTC, dedece35 requested changes
please check @Djoums review notes

2025-01-12 22:05 UTC, dedece35 commented
@Djoums, because of no answer by @ElyesFakhar ... could you create a new PR with the content of @ElyesFakhar PR and add the lacks, please ?
Thus, we can close this PR and quickly your PR.
This is what I do when I see no answer by commiter during a few months.
What do you think about it ?

2025-01-13 00:01 UTC, Djoums commented
Yes, I've postponed this long enough 🙃

2025-01-18 04:31 UTC, closed without merging