docs: 📝 "++i" statement is not so bad
green-code-initiative/creedengo-rules-specifications pull request #317
Opened 2024-05-30 08:48 UTC by pataluc

Documentation for EC67

green-code-initiative/ecoCode-java#4

2024-05-31 19:36 UTC, dedece35 approved these changes

2024-05-31 19:37 UTC, dedece35 requested changes
ok for me, but there is a conflict, please correct it before my approve

2024-06-03 16:47 UTC, dedece35 commented
PR converted to Draft becasue of waiting for following PRs : 
- https://github.com/green-code-initiative/ecoCode-java/pull/44
- https://github.com/green-code-initiative/ecoCode-java-test-project/pull/22

2025-05-21 06:48 UTC, pataluc commented
#Challenge2025, to review by @dedece35 and @cyChop ;)

2025-05-21 08:53 UTC, JulienPlanque approved these changes
Good for me

2025-05-25 08:48 UTC, utarwyn approved these changes

2025-05-25 20:59 UTC, dedece35 approved these changes

2025-05-25 21:01 UTC, merged

2025-05-25 21:02 UTC, dedece35 commented
thank you @pataluc ! good job !